Repository cloudquery-policies/aws, pull requests merged in 2022-01, with the labels that each got.

#93 docs: Update README after policy syntax changes
  README.md
Labels: docs

#97 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/policy_lint.yml
  .github/workflows/pr_title.yml
Labels: ignore-for-release

#98 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint.yml
  .github/workflows/pr_title.yml
Labels: ignore-for-release

#99 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
  .github/workflows/pr_title.yml
  .sqlfluff
Labels: ignore-for-release

#100 chore: Update docs script
  foundational_security/docs/codebuild.md
  tools/createFoundationalSecurityDocs.py
Labels: ignore-for-release

#101 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
  .github/workflows/lint.yml
Labels: ignore-for-release

#102 chore: Synced file(s) with cloudquery/.github
  .github/workflows/schema_validation.yml
Labels: ignore-for-release

#104 fix: Fixed queries related to `aws_rds_clusters` changes
  cis_v1.2.0/policy.hcl
  foundational_security/policy.hcl
  pci_dss_v3.2.1/policy.hcl
  policy.hcl
  public_egress/policy.hcl
  publicly_available/policy.hcl
  queries/autoscaling/autoscaling_groups_elb_check.sql
  queries/codebuild/check_environment_variables.sql
  queries/cq_views/api_gateway_method_settings.sql
  queries/dynamodb/autoscale_or_ondemand.sql
  queries/ec2/ebs_snapshot_permissions_check.sql
  queries/ec2/sgs_all_access_to_port_22.sql
  queries/iam/no_star.sql
  queries/rds/amazon_aurora_clusters_should_have_backtracking_enabled.sql
  queries/rds/iam_authentication_should_be_configured_for_rds_clusters.sql
  queries/rds/rds_clusters_should_have_deletion_protection_enabled.sql
  queries/rds/rds_databases_and_clusters_should_not_use_a_database_engine_default_port.sql
  queries/rds/rds_db_clusters_should_be_configured_for_multiple_availability_zones.sql
  queries/rds/rds_db_clusters_should_be_configured_to_copy_tags_to_snapshots.sql
  queries/rds/rds_event_notifications_subscription_should_be_configured_for_critical_cluster_events.sql
  queries/s3/deny_http_requests.sql
  queries/s3/publicly_readable_buckets.sql
  queries/s3/publicly_writable_buckets.sql
  queries/s3/restrict_cross_account_actions.sql
  queries/secretsmanager/remove_unused_secrets_manager_secrets.sql
  queries/secretsmanager/secrets_should_be_rotated_within_a_specified_number_of_days.sql
Labels: fix
