Repository cloudquery-policies/aws, pull requests merged in 2022-03, with the labels that each got.

#111 fix: Command Syntax
  cis_v1.2.0/README.md
  pci_dss_v3.2.1/README.md
Labels: fix

#114 fix: Remove CIS control name from title
  cis_v1.2.0/section_1.hcl
  cis_v1.2.0/section_2.hcl
  cis_v1.2.0/section_3.hcl
  cis_v1.2.0/section_4.hcl
Labels: fix

#113 fix: Check a boolean field with "IS NOT FALSE" instead of "IS NOT NULL"
  publicly_available/policy.hcl
Labels: fix

#112 fix: Handle Singular IAM Statement in Policy
  queries/iam/no_star.sql
  queries/iam/policies_with_admin_rights.sql
  queries/iam/wildcard_access_policies.sql
  queries/kms/customer_policy_blocked_kms_actions.sql
  queries/lambda/lambda_function_prohibit_public_access.sql
  queries/s3/deny_http_requests.sql
  queries/s3/publicly_readable_buckets.sql
  queries/s3/publicly_writable_buckets.sql
  queries/s3/restrict_cross_account_actions.sql
Labels: fix

#116 fix: SSL Query for API Gateway
  queries/apigateway/api_gw_ssl_enabled.sql
  queries/cq_views/api_gateway_method_settings.sql
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/203a2515-19c2-424a-b696-59a7e1613f9d/description
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/203a2515-19c2-424a-b696-59a7e1613f9d/snapshot_data.csv
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/203a2515-19c2-424a-b696-59a7e1613f9d/table_aws_apigateway_rest_api_stages.csv
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/28612fb7-f1b2-4532-9148-7cca635ff9a4/description
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/28612fb7-f1b2-4532-9148-7cca635ff9a4/snapshot_data.csv
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/28612fb7-f1b2-4532-9148-7cca635ff9a4/table_aws_apigateway_rest_api_stages.csv
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/b41a1fd6-b67b-4f85-a89d-74291ac20beb/description
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/b41a1fd6-b67b-4f85-a89d-74291ac20beb/snapshot_data.csv
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/b41a1fd6-b67b-4f85-a89d-74291ac20beb/table_aws_apigateway_rest_api_stages.csv
  tools/find-sensitive-strings.go
Labels: fix

#108 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/lint.yml
  .github/workflows/lint_golang.yml
Labels: ignore-for-release

#118 chore: Synced file(s) with cloudquery/.github
  .github/workflows/README
  .github/workflows/lint_golang.yml
Labels: ignore-for-release

#117 feat: Run Snapshot Tests
  .github/workflows/snapshot_test.yml
  .gitignore
  test/snapshot-data/foundational_security/apigateway/ApiGateway.2/tests/203a2515-19c2-424a-b696-59a7e1613f9d/table_aws_apigateway_rest_api_stages.csv
Labels: feat

#122 chore: Explicitly define views everywhere they are used
  cis_v1.2.0/policy.hcl
  cis_v1.2.0/section_3.hcl
  foundational_security/services/ec2.hcl
  pci_dss_v3.2.1/policy.hcl
Labels: ignore-for-release
